### PR TITLE
Connect api

### PR DESCRIPTION
**Pull request by hwysocki22**
Reconnected frontend and backend via api call

### CODE REVIEW

**Review by jamaball — APPROVED** [review]
Good job connecting the database to the front end, ow we dont need to use mock data :)

**Comment by excelguruson** [comment]
Great job connecting up the database and setting up these important functions for plotting the data.

**Comment by Owen-Huggins** [comment]
Establishing the backend and organizing the data have been super helpful for the frontend!

**Comment by EHaarer** [comment]
Good way to manage processing the GeoJson from PostgreSQL server, much better so we can dockerize it later on to stop it from needing to be run locally every time

**Pull request merged**
