### PR TITLE
Map plotting

### PR DESCRIPTION
**Pull request by hwysocki22**
Map points draw from the database

### CODE REVIEW

**Comment by Owen-Huggins** [comment]
Great way of allowing us to pull the data from the database!

**Review by jamaball — APPROVED** [review]
Good job getting the data into postGIS and seperating POST and GET functionality, we may need to remove one of the two requirements files in the future.

**Comment by excelguruson** [comment]
Great job making the points show up relative to our database. I'm glad the temporary hardcoded solution is fixed!

**Comment by EHaarer** [comment]
BE CAREFUL we need to make sure all finalized categories line up for when Amanda gives us the finalized database. If anything conflicts make sure to check it here especially if they want us to add more categories/handle addresses rather than just coordinates

**Pull request merged**
